import {
  EXEC_003_PERMISSION_ASSIGNMENTS,
  type Exec003LegacyGuardKind,
  type Exec003PermissionKey,
} from "@/lib/auth/exec-003-permission-assignments";

export const EXEC_003_EVIDENCE_IDENTITY = Object.freeze({
  commitSha: "PENDING FINAL VALIDATION",
  ciRun: "PENDING FINAL VALIDATION",
  checkoutMode: "PENDING FINAL VALIDATION",
  syntheticMergeSha: "PENDING FINAL VALIDATION",
  baseSha: "PENDING FINAL VALIDATION",
});

type ImportMode = "STATIC" | "DYNAMIC_ACTUAL";

type EvidenceBinding = {
  testFile: string;
  entryPointModule: string;
  entryPointExport: string;
  entryPointLocalName: string;
  importMode: ImportMode;
  allowTestName: string;
  denyTestName: string;
  downstreamSymbol: string | null;
  finalGuardModule: string | null;
  forbiddenMockedGuardSymbol: string | null;
  requiredAllowCase: string;
  requiredDenyCase: string;
};

const EVIDENCE_BINDINGS = {
  "EXEC-003-C01-O01": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p0.test.ts",
    entryPointModule: "@/app/api/properties/[id]/request-finance/route",
    entryPointExport: "POST",
    entryPointLocalName: "requestFinance",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C01-O01 reaches the audit boundary after authorization",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C01-O01 denies before audit when the database role is rejected",
    downstreamSymbol: "serviceMocks.writeAuditLog",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "active user and tenant reach audit write",
    requiredDenyCase: "missing database user blocks audit write",
  },
  "EXEC-003-C02-O01": {
    testFile: "tests/foundation/g5-exec-003-signed-boundary-behavior.test.ts",
    entryPointModule: "@/app/api/revenue-integrity/webhook/[provider]/route",
    entryPointExport: "POST",
    entryPointLocalName: "revenueWebhook",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C02-O01 accepts a valid provider HMAC without a user-session boundary",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C02-O01 rejects an invalid provider HMAC through the real signed boundary",
    downstreamSymbol: null,
    finalGuardModule: null,
    forbiddenMockedGuardSymbol: null,
    requiredAllowCase: "valid provider HMAC is accepted",
    requiredDenyCase: "invalid provider HMAC is rejected",
  },
  "EXEC-003-C03-O01": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-pilot.test.ts",
    entryPointModule: "@/app/api/v1/contracts/[id]/cancel/route",
    entryPointExport: "POST",
    entryPointLocalName: "cancelContract",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL C03 reaches the real mutation boundary after authorization",
    denyTestName: "DIRECT_BEHAVIORAL C03 returns 403 when the current database role is denied",
    downstreamSymbol: "domainMocks.cancelDraftContract",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "allowed current database role reaches cancellation",
    requiredDenyCase: "disallowed current database role blocks cancellation",
  },
  "EXEC-003-C04-O01": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-pilot.test.ts",
    entryPointModule: "@/app/api/v1/contracts/[id]/invoices/route",
    entryPointExport: "GET",
    entryPointLocalName: "listContractInvoices",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL C04 reaches the tenant-scoped read after Cookie authorization",
    denyTestName: "DIRECT_BEHAVIORAL C04 returns 403 before data access when the database denies",
    downstreamSymbol: "prismaMocks.invoiceFindMany",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "Cookie identity plus real database decision reaches read",
    requiredDenyCase: "missing database user blocks read",
  },
  "EXEC-003-C04-O02": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p0.test.ts",
    entryPointModule: "@/app/api/v1/contracts/[id]/invoices/route",
    entryPointExport: "POST",
    entryPointLocalName: "issueContractInvoice",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C04-O02 reaches invoice issuance after Cookie authorization",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C04-O02 keeps invoice issuance Cookie-only",
    downstreamSymbol: "domainMocks.signContract",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "Cookie identity plus real database decision reaches issuance",
    requiredDenyCase: "Bearer-only identity blocks issuance",
  },
  "EXEC-003-C05-O01": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p0.test.ts",
    entryPointModule: "@/app/api/v1/contracts/[id]/payment-plan/route",
    entryPointExport: "GET",
    entryPointLocalName: "readPaymentPlan",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C05-O01 reaches the tenant-scoped payment-plan read",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C05-O01 denies payment-plan read before Prisma",
    downstreamSymbol: "prismaMocks.paymentPlanFindFirst",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "active user and tenant reach payment-plan read",
    requiredDenyCase: "missing database user blocks payment-plan read",
  },
  "EXEC-003-C05-O02": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p0.test.ts",
    entryPointModule: "@/app/api/v1/contracts/[id]/payment-plan/route",
    entryPointExport: "PUT",
    entryPointLocalName: "updatePaymentPlan",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C05-O02 reaches payment-plan update after authorization",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C05-O02 denies update before the domain mutation",
    downstreamSymbol: "domainMocks.configurePaymentPlan",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "allowed role reaches payment-plan update",
    requiredDenyCase: "disallowed role blocks payment-plan update",
  },
  "EXEC-003-C05-O03": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p0.test.ts",
    entryPointModule: "@/app/api/v1/contracts/[id]/payment-plan/route",
    entryPointExport: "POST",
    entryPointLocalName: "createPaymentPlan",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C05-O03 reaches payment-plan creation after authorization",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C05-O03 denies creation before the domain mutation",
    downstreamSymbol: "domainMocks.ensureDefaultPaymentPlan",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "allowed role reaches payment-plan creation",
    requiredDenyCase: "disallowed role blocks payment-plan creation",
  },
  "EXEC-003-C06-O01": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p0.test.ts",
    entryPointModule: "@/app/api/v1/contracts/[id]/restructure/route",
    entryPointExport: "POST",
    entryPointLocalName: "restructurePaymentPlanRoute",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C06-O01 reaches restructuring after Cookie authorization",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C06-O01 rejects Bearer-only access on restructure",
    downstreamSymbol: "domainMocks.restructurePaymentPlan",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "Cookie identity plus real database decision reaches restructure",
    requiredDenyCase: "Bearer-only identity blocks restructure",
  },
  "EXEC-003-C07-O01": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p0.test.ts",
    entryPointModule: "@/app/api/v1/contracts/[id]/sign/route",
    entryPointExport: "POST",
    entryPointLocalName: "signContractRoute",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C07-O01 reaches signing after authorization",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C07-O01 denies signing before the domain operation",
    downstreamSymbol: "domainMocks.signContract",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "allowed role reaches signing",
    requiredDenyCase: "disallowed role blocks signing",
  },
  "EXEC-003-C08-O01": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p0.test.ts",
    entryPointModule: "@/app/api/v1/invoices/[id]/paylink/create/route",
    entryPointExport: "POST",
    entryPointLocalName: "createPaylink",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C08-O01 reaches the tenant-scoped invoice lookup after authorization",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C08-O01 returns 403 when Legacy database roles deny",
    downstreamSymbol: "prismaMocks.invoiceFindFirst",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "allowed role reaches Paylink invoice lookup",
    requiredDenyCase: "disallowed role blocks invoice lookup",
  },
  "EXEC-003-C09-O01": {
    testFile: "tests/foundation/g5-exec-003-signed-boundary-behavior.test.ts",
    entryPointModule: "@/app/api/v1/leads/webhook/route",
    entryPointExport: "POST",
    entryPointLocalName: "leadsWebhook",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C09-O01 accepts the real timestamped HMAC and reaches tenant-scoped lead creation",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C09-O01 rejects an invalid leads HMAC before lead creation",
    downstreamSymbol: "leadMocks.leadCreate",
    finalGuardModule: null,
    forbiddenMockedGuardSymbol: null,
    requiredAllowCase: "valid timestamped HMAC reaches lead creation",
    requiredDenyCase: "invalid HMAC blocks lead creation",
  },
  "EXEC-003-C10-O01": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p0.test.ts",
    entryPointModule: "@/app/api/v1/leases/[id]/invoices/route",
    entryPointExport: "POST",
    entryPointLocalName: "createLeaseInvoice",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C10-O01 reaches the tenant-scoped lease lookup",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C10-O01 keeps lease invoice creation Cookie-only",
    downstreamSymbol: "prismaMocks.rentalLeaseFindFirst",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "Cookie identity plus real database decision reaches lease lookup",
    requiredDenyCase: "Bearer-only identity blocks lease lookup",
  },
  "EXEC-003-C11-O01": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p0.test.ts",
    entryPointModule: "@/app/api/v1/settings/leads-webhook/route",
    entryPointExport: "GET",
    entryPointLocalName: "readLeadsWebhookSettings",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C11-O01 reaches the tenant-scoped settings read",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C11-O01 enforces ADMIN before reading webhook settings",
    downstreamSymbol: "prismaMocks.tenantFindFirst",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "ADMIN reaches settings read",
    requiredDenyCase: "non-ADMIN role blocks settings read",
  },
  "EXEC-003-C11-O02": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p0.test.ts",
    entryPointModule: "@/app/api/v1/settings/leads-webhook/route",
    entryPointExport: "POST",
    entryPointLocalName: "rotateLeadsWebhookSecret",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C11-O02 reaches credential rotation only after ADMIN authorization",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C11-O02 denies credential rotation before the transaction",
    downstreamSymbol: "prismaMocks.transaction",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "ADMIN reaches rotation transaction",
    requiredDenyCase: "non-ADMIN role blocks rotation transaction",
  },
  "EXEC-003-C12-O01": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p1-mutation.test.ts",
    entryPointModule: "@/app/api/v1/accounting/journal-entries/[id]/route",
    entryPointExport: "GET",
    entryPointLocalName: "readJournalEntry",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C12-O01 reaches tenant-scoped journal-entry read",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C12-O01 denies journal-entry read before Prisma",
    downstreamSymbol: "prismaMocks.journalEntryFindFirst",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "active user and tenant reach journal read",
    requiredDenyCase: "missing database user blocks journal read",
  },
  "EXEC-003-C12-O02": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p1-mutation.test.ts",
    entryPointModule: "@/app/api/v1/accounting/journal-entries/[id]/route",
    entryPointExport: "POST",
    entryPointLocalName: "reverseJournalEntryRoute",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C12-O02 reaches reversal after ADMIN authorization",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C12-O02 denies reversal before the mutation",
    downstreamSymbol: "accountingMocks.reverseJournalEntry",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "ADMIN reaches reversal",
    requiredDenyCase: "non-ADMIN role blocks reversal",
  },
  "EXEC-003-C13-O01": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p1-mutation.test.ts",
    entryPointModule: "@/app/api/v1/accounting/seed/route",
    entryPointExport: "POST",
    entryPointLocalName: "seedAccounting",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C13-O01 reaches tenant-scoped accounting seed",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C13-O01 denies accounting seed before execution",
    downstreamSymbol: "accountingMocks.seedChartOfAccounts",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "ADMIN reaches accounting seed",
    requiredDenyCase: "non-ADMIN role blocks accounting seed",
  },
  "EXEC-003-C14-O01": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p1-mutation.test.ts",
    entryPointModule: "@/app/api/v1/automation/workflows/route",
    entryPointExport: "GET",
    entryPointLocalName: "readWorkflows",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C14-O01 reaches tenant-scoped workflow read",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C14-O01 rejects Bearer-only workflow reads",
    downstreamSymbol: "prismaMocks.workflowFindMany",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "Cookie identity plus real database decision reaches workflow read",
    requiredDenyCase: "Bearer-only identity blocks workflow read",
  },
  "EXEC-003-C14-O02": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p1-mutation.test.ts",
    entryPointModule: "@/app/api/v1/automation/workflows/route",
    entryPointExport: "POST",
    entryPointLocalName: "createWorkflow",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C14-O02 reaches workflow creation after Cookie authorization",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C14-O02 denies workflow creation before Prisma",
    downstreamSymbol: "prismaMocks.workflowCreate",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "Cookie identity plus real database decision reaches workflow creation",
    requiredDenyCase: "missing database user blocks workflow creation",
  },
  "EXEC-003-C15-O01": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p1-mutation.test.ts",
    entryPointModule: "@/app/api/v1/maintenance/route",
    entryPointExport: "GET",
    entryPointLocalName: "readMaintenanceTickets",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C15-O01 reaches tenant-scoped maintenance read",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C15-O01 rejects Bearer-only maintenance reads",
    downstreamSymbol: "prismaMocks.ticketFindMany",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "Cookie identity plus real database decision reaches maintenance read",
    requiredDenyCase: "Bearer-only identity blocks maintenance read",
  },
  "EXEC-003-C15-O02": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p1-mutation.test.ts",
    entryPointModule: "@/app/api/v1/maintenance/route",
    entryPointExport: "POST",
    entryPointLocalName: "createMaintenanceTicket",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C15-O02 reaches maintenance creation after Cookie authorization",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C15-O02 denies maintenance creation before Prisma",
    downstreamSymbol: "prismaMocks.ticketCreate",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "Cookie identity plus real database decision reaches maintenance creation",
    requiredDenyCase: "missing database user blocks maintenance creation",
  },
  "EXEC-003-C16-O01": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p1-mutation.test.ts",
    entryPointModule: "@/app/api/v1/maintenance/[id]/route",
    entryPointExport: "PATCH",
    entryPointLocalName: "updateMaintenanceTicket",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C16-O01 reaches tenant-scoped maintenance update",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C16-O01 denies maintenance update before Prisma",
    downstreamSymbol: "prismaMocks.ticketUpdate",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "Cookie identity plus real database decision reaches maintenance update",
    requiredDenyCase: "missing Cookie identity blocks maintenance update",
  },
  "EXEC-003-C17-O01": {
    testFile: "tests/foundation/g5-exec-003-delegated-boundary-behavior.test.ts",
    entryPointModule: "@/app/actions/aiClient",
    entryPointExport: "generateAIInsight",
    entryPointLocalName: "generateAIInsight",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C17-O01 delegates allow behavior to requireAgentAccess",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C17-O01 preserves delegated denial without a shared-guard bypass",
    downstreamSymbol: "providerMocks.generateAgentJson",
    finalGuardModule: "@/lib/agents/access",
    forbiddenMockedGuardSymbol: "requireAgentAccess",
    requiredAllowCase: "active tenant user with allowed role reaches AI provider",
    requiredDenyCase: "disallowed role blocks AI provider",
  },
  "EXEC-003-C18-O01": {
    testFile: "tests/foundation/g5-exec-003-exact-claim-boundary-behavior.test.ts",
    entryPointModule: "@/app/actions/logs",
    entryPointExport: "clearSystemLogsAction",
    entryPointLocalName: "clearSystemLogsAction",
    importMode: "DYNAMIC_ACTUAL",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C18-O01 keeps the exact legacy Admin claim",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C18-O01 keeps the exact legacy Admin claim",
    downstreamSymbol: null,
    finalGuardModule: null,
    forbiddenMockedGuardSymbol: null,
    requiredAllowCase: "exact Admin claim succeeds",
    requiredDenyCase: "ADMIN claim is denied",
  },
  "EXEC-003-C19-O01": {
    testFile: "tests/foundation/g5-exec-003-exact-claim-boundary-behavior.test.ts",
    entryPointModule: "@/app/actions/logs",
    entryPointExport: "triggerMockErrorAction",
    entryPointLocalName: "triggerMockErrorAction",
    importMode: "DYNAMIC_ACTUAL",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C19-O01 keeps the exact legacy Admin claim",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C19-O01 keeps the exact legacy Admin claim",
    downstreamSymbol: "logMocks.loggerError",
    finalGuardModule: null,
    forbiddenMockedGuardSymbol: null,
    requiredAllowCase: "exact Admin claim reaches logger",
    requiredDenyCase: "ADMIN claim blocks logger",
  },
  "EXEC-003-C20-O01": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-pilot.test.ts",
    entryPointModule: "@/app/api/v1/accounting/payables/route",
    entryPointExport: "GET",
    entryPointLocalName: "readPayables",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL C20 reaches the tenant-scoped sensitive read after authorization",
    denyTestName: "DIRECT_BEHAVIORAL C20 returns 403 for an unknown or database-denied role",
    downstreamSymbol: "accountingMocks.getSupplierBalances",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "active user and tenant reach payables read",
    requiredDenyCase: "missing database user blocks payables read",
  },
  "EXEC-003-C21-O01": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-pilot.test.ts",
    entryPointModule: "@/app/api/v1/contracts/[id]/pdf/route",
    entryPointExport: "GET",
    entryPointLocalName: "readContractPdf",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL C21 reaches the tenant-scoped PDF lookup after authorization",
    denyTestName: "DIRECT_BEHAVIORAL C21 keeps the sensitive PDF read Cookie-only",
    downstreamSymbol: "prismaMocks.contractFindFirst",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "Cookie identity plus real database decision reaches PDF lookup",
    requiredDenyCase: "Bearer-only identity blocks PDF lookup",
  },
  "EXEC-003-C22-O01": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p1-sensitive-read.test.ts",
    entryPointModule: "@/app/api/v1/invoices/[id]/paylink/status/route",
    entryPointExport: "GET",
    entryPointLocalName: "readPaylinkStatus",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C22-O01 reaches the tenant-scoped Paylink status lookup",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C22-O01 returns 403 when the database user is missing",
    downstreamSymbol: "prismaMocks.invoiceFindFirst",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "active user and tenant reach Paylink status lookup",
    requiredDenyCase: "missing database user blocks lookup",
  },
  "EXEC-003-C23-O01": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p1-sensitive-read.test.ts",
    entryPointModule: "@/app/api/v1/invoices/[id]/pdf/route",
    entryPointExport: "GET",
    entryPointLocalName: "readInvoicePdf",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C23-O01 reaches the tenant-scoped invoice PDF lookup",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C23-O01 rejects Bearer-only invoice PDF access",
    downstreamSymbol: "prismaMocks.invoiceFindFirst",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "Cookie identity plus real database decision reaches invoice PDF lookup",
    requiredDenyCase: "Bearer-only identity blocks invoice PDF lookup",
  },
  "EXEC-003-C24-O01": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-p1-sensitive-read.test.ts",
    entryPointModule: "@/app/api/v1/invoices/[id]/qr/route",
    entryPointExport: "GET",
    entryPointLocalName: "readInvoiceQr",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL EXEC-003-C24-O01 reaches the tenant-scoped invoice QR lookup",
    denyTestName: "DIRECT_BEHAVIORAL EXEC-003-C24-O01 rejects Bearer-only invoice QR access",
    downstreamSymbol: "prismaMocks.invoiceFindFirst",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "Cookie identity plus real database decision reaches invoice QR lookup",
    requiredDenyCase: "Bearer-only identity blocks invoice QR lookup",
  },
  "EXEC-003-C25-O01": {
    testFile: "tests/foundation/g5-exec-003-contract-behavior-pilot.test.ts",
    entryPointModule: "@/app/actions/rentals",
    entryPointExport: "getRentalContractsAction",
    entryPointLocalName: "getRentalContractsAction",
    importMode: "STATIC",
    allowTestName: "DIRECT_BEHAVIORAL C25 reaches the tenant-scoped Server Action read after authorization",
    denyTestName: "DIRECT_BEHAVIORAL C25 has no Platform Owner bypass when the database denies",
    downstreamSymbol: "prismaMocks.contractFindMany",
    finalGuardModule: "@/lib/api-auth-guard",
    forbiddenMockedGuardSymbol: "hasDatabaseRole",
    requiredAllowCase: "active tenant user reaches rental contract read",
    requiredDenyCase: "platform-owner identity without tenant database user is denied",
  },
} as const satisfies Record<string, EvidenceBinding>;

export type Exec003BehaviorEvidence = {
  contractId: string;
  operationId: string;
  entryPoint: string;
  entryPointModule: string;
  entryPointExport: string;
  entryPointLocalName: string;
  importMode: ImportMode;
  testFile: string;
  allowTestName: string;
  denyTestName: string;
  evidenceClass: "DIRECT_BEHAVIORAL";
  boundaryType: Exec003LegacyGuardKind;
  permissionKey: Exec003PermissionKey;
  legacyRoles: readonly string[];
  requiredAllowCase: string;
  requiredDenyCase: string;
  securityDecisionDependency: string;
  downstreamSymbol: string | null;
  finalGuardModule: string | null;
  forbiddenMockedGuardSymbol: string | null;
};

export const EXEC_003_BEHAVIOR_EVIDENCE: readonly Exec003BehaviorEvidence[] =
  EXEC_003_PERMISSION_ASSIGNMENTS.flatMap((contract) =>
    contract.operations.map((operation, index) => {
      const operationId = `${contract.contractId}-O${String(index + 1).padStart(2, "0")}`;
      const binding = EVIDENCE_BINDINGS[
        operationId as keyof typeof EVIDENCE_BINDINGS
      ];
      if (!binding) {
        throw new Error(`Missing evidence binding for ${operationId}`);
      }

      return Object.freeze({
        contractId: contract.contractId,
        operationId,
        entryPoint: `${operation.method} ${contract.routeOrContract}`,
        entryPointModule: binding.entryPointModule,
        entryPointExport: binding.entryPointExport,
        entryPointLocalName: binding.entryPointLocalName,
        importMode: binding.importMode,
        testFile: binding.testFile,
        allowTestName: binding.allowTestName,
        denyTestName: binding.denyTestName,
        evidenceClass: "DIRECT_BEHAVIORAL" as const,
        boundaryType: operation.legacyGuardKind,
        permissionKey: operation.permissionKey,
        legacyRoles: operation.legacyAllowedRoles,
        requiredAllowCase: binding.requiredAllowCase,
        requiredDenyCase: binding.requiredDenyCase,
        securityDecisionDependency:
          operation.legacyGuardKind === "DELEGATED_DATABASE_RBAC"
            ? "requireAgentAccess"
            : operation.sharedGuardEligible
              ? "hasDatabaseRole"
              : operation.legacyGuardKind,
        downstreamSymbol: binding.downstreamSymbol,
        finalGuardModule: binding.finalGuardModule,
        forbiddenMockedGuardSymbol: binding.forbiddenMockedGuardSymbol,
      });
    }),
  );
