export const dashboardCopy = {
  AR: {
    dashboardEyebrow: "لوحة القيادة التشغيلية",
    welcome: "مرحبًا",
    askOrca: "اسأل ORCA",
    refreshData: "تحديث البيانات",
    decisionCenterTitle: "مركز القرار الذكي",
    decisionCenterDescription: "إشارات تشغيلية من البيانات الفعلية، من دون تنبؤ أو قرار مصطنع.",
    operationalSignals: "أولويات اليوم",
    noOperationalSignals: "لا توجد إشارات تشغيلية عاجلة ضمن البيانات الحالية.",
    agentStatusTitle: "حالة الوكلاء",
    agentStatusDescription: "الوكلاء الخمسة ومنسق الدورة Sentinel.",
    openAgents: "فتح مركز الوكلاء",
    providerNotConfigured: "مزود الذكاء الاصطناعي غير مهيأ.",
    agentsUnavailable: "تعذر تحميل حالة الوكلاء.",
    configured: "مهيأ",
    notConfigured: "غير مهيأ",
    active: "نشط",
    stopped: "متوقف",
    needsAttention: "يحتاج متابعة",
    coordinator: "منسق الدورة",
    assistantTitle: "اسأل ORCA",
    assistantDescription: "اكتب سؤالك لقراءة بيانات لوحة التحكم الحالية.",
    assistantWelcome: "مرحبًا، اسألني عن العملاء أو الجولات أو العروض أو العقود أو مسار الصفقات أو واتساب أو حالة الوكلاء.",
    assistantGeneralAnswer: "هذا ملخص الأولويات الحالية:",
    assistantInputLabel: "رسالتك إلى ORCA",
    assistantInputPlaceholder: "اكتب سؤالك هنا...",
    assistantInputHint: "Enter للإرسال، وShift+Enter لسطر جديد.",
    sendMessage: "إرسال الرسالة",
    assistantDataNotice: "الإجابة تلخص بيانات التشغيل الحالية فقط، ولا تمثل تنبؤًا آليًا أو اعتمادًا قانونيًا أو ماليًا.",
    quickQuestions: "أسئلة سريعة",
    questionPriorities: "ما أهم الأولويات اليوم؟",
    questionPipeline: "ما وضع مسار الصفقات؟",
    questionWhatsapp: "ما حالة واتساب؟",
    questionAgents: "ما حالة الوكلاء؟",
    close: "إغلاق",
    answerPlaceholder: "اختر سؤالًا لعرض الإجابة.",
    relevantAgent: "الوكيل المعني",
    overdueTasksSignal: "مهام ظاهرة متأخرة",
    unreadWhatsappSignal: "رسائل واتساب غير مقروءة",
    activeOffersSignal: "عروض نشطة تحتاج متابعة",
    newLeadsSignal: "عملاء جدد هذا الأسبوع",
    agentAttentionSignal: "وكلاء يحتاجون متابعة",
    mansour: "منصور",
    saher: "ساهر",
    sanad: "سند",
    baseer: "بصير",
    khabeer: "خبير",
    sentinel: "Sentinel",
    fallbackUser: "المستخدم",
    description: "ملخص موثوق لحركة المبيعات والعمليات اليومية.",
    today: "اليوم",
    issueContract: "إصدار عقد جديد",
    activeLeads: "العملاء النشطون",
    activeLeadsDescription: "العملاء غير المؤرشفين",
    todayTours: "جولات اليوم",
    todayToursDescription: "الجولات غير الملغاة اليوم",
    activeOffers: "العروض النشطة",
    activeOffersDescription: "عروض سارية قيد الانتظار",
    signedContracts: "العقود الموقعة",
    signedContractsDescription: "العقود الموقعة هذا الشهر",
    dataUnavailable: "تعذر تحميل البيانات",
    retry: "إعادة المحاولة",
    pipelineTitle: "مسار الصفقات",
    pipelineDescription: "تقدم الصفقات من الفرصة حتى الإغلاق اعتمادًا على السجلات الفعلية.",
    pipelineTotal: "إجمالي المسار",
    activeStages: "المراحل النشطة",
    closeRate: "نسبة الإغلاق",
    live: "مباشر",
    opportunity: "فرصة",
    tour: "جولة",
    offer: "عرض",
    contract: "عقد",
    closed: "مغلق",
    noActiveDeals: "لا توجد صفقات ضمن المسار حاليًا.",
    operationsTitle: "مركز العمليات اليومية",
    operationsDescription: "المهام والعملاء وواتساب في مساحة تشغيل واحدة.",
    tasks: "المهام العاجلة",
    recentLeads: "أحدث العملاء",
    whatsapp: "واتساب",
    viewAllTasks: "عرض جميع المهام",
    viewAllLeads: "عرض جميع العملاء",
    openWhatsapp: "فتح واتساب",
    noTasks: "لا توجد مهام متأخرة أو مستحقة اليوم.",
    noLeads: "لا يوجد عملاء حديثون.",
    noSearchResults: "لا توجد نتائج مطابقة ضمن المعاينة الحالية.",
    searchLabel: "نتائج البحث",
    overdue: "متأخرة",
    high: "عالية",
    medium: "متوسطة",
    low: "منخفضة",
    conversations: "المحادثات",
    newWhatsappLeads: "عملاء جدد خلال 7 أيام",
    unreadMessages: "رسائل غير مقروءة",
    loading: "جارٍ تحميل لوحة التحكم",
    fatalErrorTitle: "تعذر فتح لوحة التحكم",
    fatalErrorDescription: "حدث خطأ غير متوقع. أعد المحاولة دون فقدان أي بيانات.",
  },
  EN: {
    dashboardEyebrow: "Operational command dashboard",
    welcome: "Welcome",
    askOrca: "Ask ORCA",
    refreshData: "Refresh data",
    decisionCenterTitle: "Intelligent decision center",
    decisionCenterDescription: "Operational signals from real data, without fabricated predictions or decisions.",
    operationalSignals: "Today's priorities",
    noOperationalSignals: "There are no urgent operational signals in the current data.",
    agentStatusTitle: "Agent status",
    agentStatusDescription: "The five agents and the Sentinel cycle coordinator.",
    openAgents: "Open agent center",
    providerNotConfigured: "The AI provider is not configured.",
    agentsUnavailable: "Agent status could not be loaded.",
    configured: "Configured",
    notConfigured: "Not configured",
    active: "Active",
    stopped: "Stopped",
    needsAttention: "Needs attention",
    coordinator: "Cycle coordinator",
    assistantTitle: "Ask ORCA",
    assistantDescription: "Type a question to read the current dashboard data.",
    assistantWelcome: "Hello. Ask about leads, tours, offers, contracts, the deal pipeline, WhatsApp, or agent status.",
    assistantGeneralAnswer: "Here is the current priority summary:",
    assistantInputLabel: "Your message to ORCA",
    assistantInputPlaceholder: "Type your question here...",
    assistantInputHint: "Press Enter to send and Shift+Enter for a new line.",
    sendMessage: "Send message",
    assistantDataNotice: "The answer summarizes current operational data only. It is not an automated prediction or a legal or financial approval.",
    quickQuestions: "Quick questions",
    questionPriorities: "What are today's top priorities?",
    questionPipeline: "What is the deal pipeline status?",
    questionWhatsapp: "What is the WhatsApp status?",
    questionAgents: "What is the agent status?",
    close: "Close",
    answerPlaceholder: "Choose a question to display the answer.",
    relevantAgent: "Relevant agent",
    overdueTasksSignal: "Visible overdue tasks",
    unreadWhatsappSignal: "Unread WhatsApp messages",
    activeOffersSignal: "Active offers needing follow-up",
    newLeadsSignal: "New leads this week",
    agentAttentionSignal: "Agents needing attention",
    mansour: "Mansour",
    saher: "Saher",
    sanad: "Sanad",
    baseer: "Baseer",
    khabeer: "Khabeer",
    sentinel: "Sentinel",
    fallbackUser: "User",
    description: "A trusted snapshot of sales movement and daily operations.",
    today: "Today",
    issueContract: "Issue new contract",
    activeLeads: "Active leads",
    activeLeadsDescription: "Non-archived leads",
    todayTours: "Today's tours",
    todayToursDescription: "Non-cancelled tours today",
    activeOffers: "Active offers",
    activeOffersDescription: "Valid pending offers",
    signedContracts: "Signed contracts",
    signedContractsDescription: "Contracts signed this month",
    dataUnavailable: "Data could not be loaded",
    retry: "Try again",
    pipelineTitle: "Deal pipeline",
    pipelineDescription: "Deal progress from opportunity to closure, based on real records.",
    pipelineTotal: "Pipeline total",
    activeStages: "Active stages",
    closeRate: "Close rate",
    live: "Live",
    opportunity: "Opportunity",
    tour: "Tour",
    offer: "Offer",
    contract: "Contract",
    closed: "Closed",
    noActiveDeals: "There are no deals in the pipeline right now.",
    operationsTitle: "Daily operations center",
    operationsDescription: "Tasks, leads, and WhatsApp in one operational workspace.",
    tasks: "Urgent tasks",
    recentLeads: "Recent leads",
    whatsapp: "WhatsApp",
    viewAllTasks: "View all tasks",
    viewAllLeads: "View all leads",
    openWhatsapp: "Open WhatsApp",
    noTasks: "There are no overdue tasks or tasks due today.",
    noLeads: "There are no recent leads.",
    noSearchResults: "No matching results in the current preview.",
    searchLabel: "Search results",
    overdue: "Overdue",
    high: "High",
    medium: "Medium",
    low: "Low",
    conversations: "Conversations",
    newWhatsappLeads: "New leads in 7 days",
    unreadMessages: "Unread messages",
    loading: "Loading dashboard",
    fatalErrorTitle: "Dashboard could not be opened",
    fatalErrorDescription: "An unexpected error occurred. Retry without losing any data.",
  },
} as const;

const dashboardSystemTaskTitles = [
  { ar: "متابعة عرض السعر", en: "Follow up on price offer" },
  { ar: "إرسال كتيب المشروع", en: "Send project brochure" },
  { ar: "متابعة العرض المقدم", en: "Follow up on submitted offer" },
  { ar: "متابعة", en: "Follow-up" },
] as const;

function normalizeDashboardTaskTitle(value: string): string {
  return value.trim().replace(/\s+/g, " ").toLocaleLowerCase();
}

export function localizeDashboardTaskTitle(
  title: string,
  locale: "ar" | "en",
): string {
  const normalizedTitle = normalizeDashboardTaskTitle(title);
  const match = dashboardSystemTaskTitles.find(
    (entry) =>
      normalizeDashboardTaskTitle(entry.ar) === normalizedTitle ||
      normalizeDashboardTaskTitle(entry.en) === normalizedTitle,
  );

  return match ? match[locale] : title;
}

export type DashboardCopy = (typeof dashboardCopy)[keyof typeof dashboardCopy];
