-- Prerequisites: WhatsApp enums created before Foundation migration
-- Use DO blocks to protect against duplicate_object errors

DO $$ BEGIN CREATE TYPE "WhatsAppConnectionStatus" AS ENUM ('DISCONNECTED','SIGNUP_PENDING','TOKEN_EXCHANGED','ASSETS_VERIFIED','WEBHOOK_SUBSCRIBED','ACTIVE','REAUTH_REQUIRED','SUSPENDED','DISCONNECTING','DISCONNECT_PENDING','FAILED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "WhatsAppSignupSessionStatus" AS ENUM ('PENDING','COMPLETED','EXPIRED','FAILED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "WhatsAppWebhookEnvelopeStatus" AS ENUM ('RECEIVED','PROCESSED','INVALID_SIGNATURE','QUARANTINED','DISCARDED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "WhatsAppWebhookEventType" AS ENUM ('INBOUND_MESSAGE','STATUS_UPDATE','UNKNOWN'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "WhatsAppWebhookEventStatus" AS ENUM ('PENDING','PROCESSED','QUARANTINED','DLQ','RETRYING'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "WhatsAppTemplateCategory" AS ENUM ('MARKETING','UTILITY','AUTHENTICATION'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "WhatsAppTemplateSyncStatus" AS ENUM ('APPROVED','REJECTED','PENDING','PAUSED','DISABLED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "WhatsAppIntegrationAuditAction" AS ENUM ('CONNECTED','DISCONNECTED','TOKEN_ROTATED','SIGNUP_INITIATED','SIGNUP_COMPLETED','SIGNUP_FAILED','PHONE_ADDED','PHONE_REMOVED','PRIMARY_CHANGED','CREDENTIAL_EXPIRED','AUTOMATION_ENABLED','AUTOMATION_DISABLED','TEMPLATE_SYNCED','KILL_SWITCH_ENGAGED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
